/* ---------------- 終章 ---------------- */
SCENARIO.fin = [
 {chapTitle:'終章 あさやけ編'},
 {card:['FINAL CHAPTER','あさやけ編','DAY 13 ／ 8月13日',6]},
 {day:13},
 {nar:'十三日目。街は静かで、霧が濃い。明日は、十年前の火災の日。'},
 {nar:'あなたは相談室に三台の電話を並べた。回線を三つ、同時に開くために。'},
 {sys:'準備できることは、あと少しだけあります。'},

 {ch:[
  {t:'ヒュウとネオに、連携を頼む',tag:'発信',req:{and:[{f:'HYU_EYE_01'},{f:'NEO_ALLY_01'}]},
   set:{NEO_HYU_01:1},go:'prep_neo'},
  {t:'ムニに、逃げ方の続きを教える',tag:'発信',go:'prep_mun'},
  {t:'何もせず、明日を待つ',tag:'保留',go:'d14'}
 ]},

 {n:'prep_neo'},
 {noise:2},
 {call:{who:'ネオ／ヒュウ',c:'NEO',num:'▓▓▓-▓▓▓▓'}},
 {c:'NEO',say:'……話は聞いた。裂け目は内側からも閉じられる。だが一人では、閉じた瞬間に私も消える。'},
 {c:'HYU',say:'ですから、私が座標を視ます。ネオ殿が斬り、私が指し、あなたが繋ぐ。'},
 {c:'HYU',say:'……ふふ。三人がかりでようやく一人前とは、我ながら美しくない話ですが。'},
 {ch:[
  {t:'三人で一人前なら、それでいい。誰も欠けないやり方を選ぼう',tag:'連携',
   eff:{'HYU.trust':15,'NEO.trust':15},set:{NEO_HYU_01:1},go:'prep_neo2'},
  {t:'ヒュウ。無理はしないで',tag:'配慮',eff:{'HYU.trust':8},set:{NEO_HYU_01:1},go:'prep_neo2'}
 ]},

 {n:'prep_neo2'},
 {c:'NEO',say:'……ふん。人間というのは、面倒な繋がり方をするものだな。'},
 {c:'NEO',say:'だが、悪くない。'},
 {par:{c:'NEO',trust:10}},
 {par:{c:'HYU',fear:-20,stress:-20}},
 {hang:'通話終了',hangKind:'normal'},
 {go:'prep_mun'},

 {n:'prep_mun'},
 {clock:'03:33'},
 {ring:'old'},
 {ch:[
  {t:'受話器を取る',tag:'受電',go:'prep_mun2'},
  {t:'取らない',tag:'見送り',inc:{MUN_CUT_XX:1},go:'d14'}
 ]},

 {n:'prep_mun2'},
 {call:{who:'ムニ(10年前)',c:'MUN',num:'0X-XXX-1994'}},
 {c:'MUN',say:'でんわのひと。……きょう、おまつりだったよ。'},
 {c:'MUN',say:'おにいちゃんと、りんごあめ、はんぶんこした。'},
 {nar:'——十年前の八月十三日。明日の夜、この子の世界は燃える。'},
 {ch:[
  {t:'ムニ。煙が出たら、どうするんだった?',tag:'確認',req:{and:[{f:'MUN_TEACH_01'},{nf:'MUN_CHK1'}]},
   eff:{'MUN.trust':8},set:{MUN_CHK1:1},go:'prep_check1'},
  {t:'ムニ。裏の物置の鍵は、消火栓の箱の中にあるよ',tag:'教える',
   hide:{and:[{loop:2},{f:'EVD_TAPE_01'}]},req:{and:[{f:'LEN_REMEMBER'},{nf:'MUN_TEACH_02'}]},
   set:{MUN_TEACH_02:1},eff:{'MUN.trust':12},go:'prep_key',
   line:'ムニ。よく聞いて。裏の物置の鍵は、廊下のいちばん奥、消火栓の箱の中にある。そこから外に出られる。'},
  {t:'怖くなったら、私の声を思い出して',tag:'教える',req:{nf:'MUN_TEACH_03'},
   eff:{'MUN.trust':15,'MUN.fear':-20},set:{MUN_TEACH_03:1},go:'prep_check3'},
  {t:'……おやすみ、ムニ',tag:'別れ',eff:{'MUN.trust':5},go:'d14'}
 ]},

 {n:'prep_check1'},
 {c:'MUN',say:'ひくくなって、はって、にげる! おぼえてるよ!'},
 {set:{MUN_TEACH_01:1}},
 {go:'prep_loop'},

 {n:'prep_key'},
 {nar:'——なぜ、あなたはその場所を知っているのか。'},
 {nar:'レニィが思い出した記憶。室井のテープ。そして、あなた自身のどこかにある、名前のない確信。'},
 {c:'MUN',say:'しょうかせんのはこ。……うん。ムニ、みたことある。ちいさいかぎでしょ?'},
 {c:'MUN',say:'おぼえた。ぜったいわすれない。'},
 {memo:['ムニに教えたこと②','裏の物置の鍵は廊下奥の消火栓の箱の中。そこから外へ出られる。']},
 {go:'prep_loop'},

 {n:'prep_check3'},
 {c:'MUN',say:'うん。でんわのひとのこえ、ちゃんとおぼえてる。'},
 {c:'MUN',say:'……ねえ。あしたも、おはなしできる?'},
 {ch:[
  {t:'できる。必ず、明日もここにいる',tag:'約束',eff:{'MUN.trust':20},set:{MUN_PROMISE2:1},go:'prep_loop'}
 ]},

 {n:'prep_loop'},
 {ch:[
  {t:'（まだ伝えることがある）',tag:'続ける',go:'prep_mun2'},
  {t:'……おやすみ、ムニ。また明日',tag:'終える',go:'d14'}
 ]},

 {n:'d14'},
 {hang:'通話終了',hangKind:'normal'},
 {day:14},
 {card:['DAY 14','8月14日','十年前と、今夜が重なる',6]},
 {noise:2},
 {nar:'十四日目。八月十四日。'},
 {nar:'霧が、建物の三階まで上がってきている。時計の秒針が、ときどき同じ場所で二度鳴る。'},
 {clock:'23:00'},
 {sys:'回線状況：不安定<br>三台の電話が、すべて同時に着信しています。'},
 {ring:'broken'},
 {still:'s14'},
 {sys:'【1】跡地 ── ジンパチ／ゲル<br>【2】渡岸 ── ネオ／ヒュウ<br>【3】0X-XXX-1994 ── ムニ（十年前）'},
 {nar:'三本。同時に。あなたの手は二本しかない。'},
 {ch:[
  {t:'【1】跡地の二人を取る',tag:'選択',go:'line1'},
  {t:'【2】渡岸を取る',tag:'選択',go:'line2'},
  {t:'【3】十年前を取る',tag:'選択',go:'line3'},
  {t:'保留を使い、三本すべてを繋いだままにする',tag:'技術',go:'line_all'}
 ]},

 {n:'line_all'},
 {nar:'あなたは保留ボタンを押し、受話器を肩に挟み、コードを絡ませながら三本を同時に開いた。'},
 {nar:'業務規程には違反している。今日だけは、どうでもいい。'},
 {set:{THREE_LINES:1}},
 {sys:'三回線 同時接続 ── 保留切替でそれぞれに応答します。'},
 {go:'line1'},

 {n:'line1'},
 {if:{nf:'GER_KNIFE_01'}, then:'ger_alone'},
 {go:'line1_join'},

 {n:'ger_alone'},
 {noise:3},
 {nar:'ゲルの携帯は、繋がらない。'},
 {nar:'折り返し発信——呼び出し音。十二回。そして、誰かが出た。'},
 {c:'KAI',nm:'灰堂',say:'ああ、この電話の持ち主かね。……残念だが、彼女はもう、こちら側だ。'},
 {hang:'相手側が切電（無音）',hangKind:'silent'},
 {life:['GER','消失']},
 {sys:'ゲル ── 消息不明'},

 {n:'line1_join'},
 {call:{who:'【1】跡地',c:'JIN',num:'跡地'}},
 {if:{f:'JIN_RUSH_01'}, then:'line1_ok', els:'line1_bad'},

 {n:'line1_bad'},
 {noise:3},
 {c:'JIN',say:'……おい、なんだよこれ、床が……ぐらぐら——'},
 {hang:'回線断（無音）',hangKind:'silent'},
 {life:['JIN','消失']},
 {sys:'ジンパチ ── 消息不明'},
 {nar:'一人で行かせてしまった。彼は、最後まで名前を呼んでいた。'},
 {go:'line2'},

 {n:'line1_ok'},
 {c:'JIN',say:'着いたぜ! 礼拝堂の跡だ。地面に……穴が開いてる。空が、逆さに見える!'},
 {if:{alive:'GER'}, then:'line1_ger', els:'line1_solo'},
 {n:'line1_ger'},
 {c:'GER',say:'灰堂もいる。装置を組んでいるな。……レニィくんも、そこだ。'},
 {go:'line1_ask'},
 {n:'line1_solo'},
 {c:'JIN',say:'……ゲルさんが来ねえ。連絡もつかねえ。くそっ、一人でも見つける。'},
 {n:'line1_ask'},
 {sec:15},
 {ch:[
  {t:'ジンパチ、灰堂に近づくな。ゲルさん、警察の到着まで記録を',tag:'指示',
   eff:{'JIN.fear':-10},set:{PLAN_A:1},go:'line1b'},
  {t:'二人とも、灰堂の左足を見て。跛行が証拠になる',tag:'指示',req:{f:'KAI_EXPOSE_01'},
   set:{PLAN_A:1},go:'line1b'},
  {t:'突っ込め',tag:'指示',eff:{'JIN.fear':20},go:'line1c'},
  {t:'（沈黙）',tag:'沈黙',silent:1,timeout:1,eff:{'JIN.fear':15},go:'line1c'}
 ]},

 {n:'line1c'},
 {noise:3},{fx:'shake'},
 {c:'JIN',say:'うおおおっ——ぐっ、な、なんだこれ、身体が——'},
 {par:{c:'JIN',fear:35}},
 {if:{f:'GER_KNIFE_01'}, then:'line1c2', els:'line1c3'},
 {n:'line1c2'},
 {c:'GER',say:'馬鹿者! 引きずってでも戻す。……お前は電話に集中しろ!'},
 {par:{c:'JIN',fear:-20}},
 {go:'line2'},
 {n:'line1c3'},
 {life:['JIN','消失']},
 {sys:'ジンパチ ── 消息不明'},
 {go:'line2'},

 {n:'line1b'},
 {c:'GER',say:'記録している。父の名誉のために、一秒残らずだ。'},
 {c:'JIN',say:'……くそ、動きてえ。でも待つ。あんたとの約束だからな。'},
 {go:'line2'},

 {n:'line2'},
 {call:{who:'【2】ネオ／ヒュウ',c:'NEO',num:'▓▓▓-▓▓▓▓'}},
 {if:{f:'NEO_HYU_01'}, then:'line2_ok', els:'line2_bad'},

 {n:'line2_bad'},
 {c:'NEO',say:'……私が独りで閉じる。それしかあるまい。'},
 {c:'NEO',say:'貴様は、貴様の電話に集中しろ。それが貴様の剣だ。'},
 {nar:'そして、通信は途絶えた。'},
 {life:['NEO','消失']},
 {if:{alive:'HYU'}, then:'line3', els:'line2_hyu'},
 {n:'line2_hyu'},
 {life:['HYU','死亡']},
 {sys:'ヒュウ ── 渡岸にて消息途絶'},
 {go:'line3'},

 {n:'line2_ok'},
 {c:'HYU',say:'座標、視えています。裂け目の根は——礼拝堂の、井戸の底です。'},
 {c:'NEO',say:'よし。私が斬る。貴様は声で二人を繋げ。ずれれば、閉じ損ねる。'},
 {ch:[
  {t:'合図は私が出します。ヒュウの「見えた」で、ネオが斬る',tag:'連携',
   eff:{'HYU.trust':10,'NEO.trust':10},set:{SYNC:1},go:'line2b'},
  {t:'ヒュウ、無理だと思ったら言って。やめる勇気も勘定に入れる',tag:'配慮',
   eff:{'HYU.trust':15},set:{SYNC:1},go:'line2b'}
 ]},

 {n:'line2b'},
 {c:'HYU',say:'……ええ。あなたの声があれば、私はこの目を、灯だと思えます。'},
 {life:['HYU','生存']},
 {life:['NEO','生存']},
 {go:'line3'},

 {n:'line3'},
 {clock:'03:31'},
 {noise:3},
 {nar:'午前三時三十一分。三本目の回線が、鳴りはじめる。'},
 {ring:'old'},
 {call:{who:'【3】ムニ(十年前)',c:'MUN',num:'0X-XXX-1994'}},
 {c:'MUN',say:'……でんわのひと。でんわのひと、たすけて。'},
 {c:'MUN',say:'けむりが、いっぱいなの。せんせいが、おきないの。'},
 {fx:'flash'},{fx:'shake'},
 {still:'s13'},
 {nar:'十年前の八月十四日、午前三時三十三分。'},
 {nar:'あの夜、この電話を、前任の相談員は切った。'},
 {nar:'——今夜は、あなたが取っている。'},
 {sys:'ここから先の一言一言が、十年前を書き換えます。'},
 {sec:20},
 {ch:[
  {t:'ムニ! 落ち着いて。煙が出たら、どうするんだった?',tag:'教える',req:{and:[{f:'MUN_TEACH_01'},{nf:'FIN_LOW'}]},
   eff:{'MUN.fear':-15,'MUN.trust':10},go:'fin_t1'},
  {t:'廊下の奥、消火栓の箱! 中の鍵で裏の物置から外へ!',tag:'教える',req:{and:[{f:'MUN_TEACH_02'},{nf:'FIN_KEY'}]},
   eff:{'MUN.fear':-15},go:'fin_t2'},
  {t:'ムニ。私の声を思い出して。いま、ここにいるから',tag:'伴走',req:{and:[{f:'MUN_TEACH_03'},{nf:'FIN_VOICE'}]},
   eff:{'MUN.fear':-25,'MUN.trust':15},go:'fin_t3'},
  {t:'いま助けを呼ぶから、動かないで!',tag:'指示',eff:{'MUN.fear':10},go:'fin_wrong'},
  {t:'（言葉が出ない）',tag:'沈黙',silent:1,timeout:1,eff:{'MUN.fear':25},go:'fin_wrong'}
 ]},

 {n:'fin_t1'},
 {c:'MUN',say:'ひくく……はって……にげる!'},
 {nar:'受話器の向こうで、小さな身体が床に伏せる音がした。'},
 {set:{FIN_LOW:1}},
 {go:'fin_loop'},

 {n:'fin_t2'},
 {c:'MUN',say:'しょうかせんのはこ! ある! かぎ、あったよ!'},
 {set:{FIN_KEY:1}},
 {go:'fin_loop'},

 {n:'fin_t3'},
 {c:'MUN',say:'……うん。きこえる。でんわのひとのこえ、きこえるよ。'},
 {c:'MUN',say:'こわくない。ムニ、こわくないよ。'},
 {set:{FIN_VOICE:1}},
 {go:'fin_loop'},

 {n:'fin_wrong'},
 {c:'MUN',say:'……うん。うごかない。まってる。'},
 {nar:'待たせてはいけない。あの夜、待った子どもは、朝を見なかった。'},
 {par:{c:'MUN',fear:20}},
 {go:'fin_loop'},

 {n:'fin_loop'},
 {if:{and:[{f:'FIN_LOW'},{f:'FIN_KEY'},{f:'FIN_VOICE'}]}, then:'fin_escape'},
 {sec:16},
 {ch:[
  {t:'（さらに声をかける）',tag:'続ける',go:'line3_again'},
  {t:'ジンパチとゲルに、跡地から呼びかけさせる',tag:'連携',req:{and:[{f:'JIN_RUSH_01'},{nf:'FIN_ALLY'}]},go:'fin_ally_call'},
  {t:'ネオとヒュウに、裂け目を閉じさせる',tag:'連携',req:{f:'NEO_HYU_01'},go:'fin_close'},
  {t:'（時間切れ）',tag:'沈黙',silent:1,timeout:1,go:'fin_close'}
 ]},

 {n:'line3_again'},
 {sec:18},
 {ch:[
  {t:'煙が出たら、どうするんだった?',tag:'教える',req:{and:[{f:'MUN_TEACH_01'},{nf:'FIN_LOW'}]},go:'fin_t1'},
  {t:'消火栓の箱の鍵! 裏の物置から外へ!',tag:'教える',req:{and:[{f:'MUN_TEACH_02'},{nf:'FIN_KEY'}]},go:'fin_t2'},
  {t:'私の声を思い出して。ここにいる',tag:'伴走',req:{and:[{f:'MUN_TEACH_03'},{nf:'FIN_VOICE'}]},go:'fin_t3'},
  {t:'ムニ、お兄ちゃんが外で待ってる。走って',tag:'励まし',req:{and:[{f:'LEN_REMEMBER'},{nf:'FIN_RUN'}]},
   eff:{'MUN.fear':-20,'MUN.trust':10},go:'fin_bro'},
  {t:'（もう言えることがない）',tag:'沈黙',silent:1,timeout:1,go:'fin_close'}
 ]},

 {n:'fin_bro'},
 {c:'MUN',say:'……おにいちゃん、そとにいるの?'},
 {c:'MUN',say:'……うん! いく!'},
 {set:{FIN_RUN:1}},
 {go:'fin_loop'},

 {n:'fin_ally_call'},
 {c:'JIN',say:'おい、聞こえるか! 井戸のとこだ! こっちだ、走ってこい!'},
 {c:'GER',say:'……こっちだ。大丈夫だ、私たちがいる。'},
 {nar:'十年の時間を跨いで、声が、声を追いかける。'},
 {set:{FIN_ALLY:1}},
 {go:'fin_loop'},

 {n:'fin_close'},
 {if:{f:'NEO_HYU_01'}, then:'fin_close_ok', els:'fin_close_bad'},

 {n:'fin_close_ok'},
 {c:'HYU',say:'見えました——いま!'},
 {c:'NEO',say:'——承知した!'},
 {fx:'flash'},{fx:'shake'},
 {nar:'金属が空気を斬る音。低周波の唸りが、ぷつりと途切れる。'},
 {noise:1},
 {set:{RIFT_CLOSED:1}},
 {go:'fin_judge'},

 {n:'fin_close_bad'},
 {noise:3},{fx:'shake'},
 {nar:'裂け目は閉じない。唸りが、街全体を舐めるように広がっていく。'},
 {go:'fin_judge'},

 {n:'fin_judge'},
 {if:{f:'MUN_SAVED'}, then:'fin_after'},
 {go:'fin_lost'},

 {n:'fin_lost'},
 {noise:3},
 {c:'MUN',say:'……でんわのひと。……ねむく、なってきちゃった。'},
 {c:'MUN',say:'……あのね。おはなし、たのしかった。'},
 {hang:'回線断（無音）',hangKind:'silent'},
 {nar:'午前三時五十一分。十年前の朝が、来る。'},
 {life:['MUN','死亡']},
 {sys:'ムニ ── 十年前の火災により死亡'},
 {nar:'あなたは受話器を握ったまま、動けなかった。'},
 {nar:'——救えなかった。今回は。'},
 {go:'fin_after'},

 {n:'fin_escape'},
 {fx:'flash'},
 {nar:'煙の下を這う音。金属の擦れる音。扉が、軋みながら開く音。'},
 {c:'MUN',say:'……でた! でんわのひと、そとにでたよ!'},
 {c:'MUN',say:'……あ。おにいちゃん! おにいちゃんもいる!'},
 {nar:'十年前の夜が、書き換わっていく。'},
 {noise:1},
 {set:{MUN_SAVED:1,STORY_TRUE_KEY:1}},
 {tlfix:['10年前 8/14','灯守園の火災。園児全員が避難し、死者はゼロ。灰堂帰一を放火と傷害の容疑で逮捕。']},
 {life:['MUN','生存']},
 {go:'fin_close'},

 {n:'fin_after'},
 {clock:'04:41'},
 {noise:0},
 {nar:'朝が来る。霧が、ゆっくりと薄くなっていく。'},
 {if:{and:[{f:'MUN_SAVED'},{f:'RIFT_CLOSED'},{f:'KAI_EXPOSE_01'},{f:'GER_KNIFE_01'},{f:'JIN_RUSH_01'}]},
  then:'ep_true', els:'ep_normal'},

 {n:'ep_normal'},
 {nar:'事件は、それぞれの形で終わった。'},
 {nar:'あなたは日誌を書き、受話器を拭き、次の夜のために席を立つ。'},
 {end:'check'},

 {n:'ep_true'},
 {still:'s15'},
 {nar:'朝焼けの相談室。'},
 {nar:'電話が鳴る。知らない番号だ。'},
 {sys:'着信 — 04:44<br>番号：080-XXXX-2214'},
 {ch:[
  {t:'受話器を取る',tag:'受電',go:'ep_true2'}
 ]},

 {n:'ep_true2'},
 {call:{who:'???',c:'MUN',num:'080-XXXX-2214'}},
 {c:'MUN',nm:'???',say:'……あの、もしもし。夜間相談の窓口で合ってますか。'},
 {nar:'少年の声。十五歳くらいの、まだ少しだけ高い声。'},
 {c:'MUN',nm:'???',say:'兄が、ここに世話になったって言うから。'},
 {c:'MUN',nm:'???',say:'あ、名乗ってなかった。ムニっていいます。',slow:1},
 {c:'MUN',nm:'ムニ(15)',say:'……はじめまして。',slow:1},
 {c:'MUN',nm:'ムニ(15)',say:'でも、なんだか、なつかしい声だね。',slow:1},
 {still:'s16'},
 {nar:'受話器を持つ手が、震えている。'},
 {nar:'十年分の朝が、いま、この部屋に届いた。'},
 {if:{and:[{f:'SEC_CALL_01'},{recs:7},{cleared:'TRUE'}]}, then:'ep_secret', els:'ep_true_end'},

 {n:'ep_true_end'},
 {end:'check'},

 {n:'ep_secret'},
 {noise:2},
 {nar:'——通話が終わったあと、録音装置が、ひとりでに回りはじめた。'},
 {still:'s17'},
 {c:'MRI',nm:'室井(録音)',say:'……七人目の子は、どこへ消えたんだ。'},
 {c:'NEO',nm:'ネオ(録音)',say:'私が拾った。渡岸の岸辺で、黒電話を抱えて泣いていた。'},
 {c:'NEO',nm:'ネオ(録音)',say:'あの子どもは、こちらでは歳を取らぬ。……いずれ、記憶をなくして戻るだろう。'},
 {nar:'そして、テープの最後。'},
 {c:'UNK',nm:'幼い声',say:'……もしもし。もしもーし。だれか、いますか。',slow:1},
 {fx:'flash'},{fx:'shake'},
 {nar:'——それは、あなた自身の声だった。'},
 {tl:['10年前 8/14','七人目の園児が渡岸へ消失。時間差の後、記憶を失って帰還——現在の相談員となる。']},
 {rel:['七人目の子','—— 同一人物','あなた']},
 {end:'SECRET'}
];
